#!/usr/bin/env node
// Writes SPRITE_TRACKER.md: every sprite slot the game has, whether its painted PNG
// exists yet, and what size to make it. Run after adding slots or sprites:
//   node tools/sprite-tracker.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { SLOTS, SCALE, sizeLabel } = await import(path.join(root, "js/sprites.js"));

const manifest = JSON.parse(fs.readFileSync(path.join(root, "assets/sprites/manifest.json"), "utf8")).files || [];
const painted = new Set(manifest.map((f) => f.replace(/\.png$/i, "")));
const world = JSON.parse(fs.readFileSync(path.join(root, "assets/world.json"), "utf8"));

const rows = SLOTS.map((s) => ({ ...s, done: painted.has(s.name) }));
for (const d of world.decor || []) {
  if (rows.some((r) => r.name === d.name)) continue;
  const [pw, ph] = d.size || [(d.w || 1) * 32, (d.h || 1) * 32];
  rows.push({ name: d.name, kind: "static", w: pw / SCALE, h: ph / SCALE, cat: d.category || "prop", since: "world.json",
    desc: `${d.title || d.name}, placed by assets/world.json at (${d.x}, ${d.y}), footprint ${d.w || 1}×${d.h || 1} tiles.`, done: painted.has(d.name) });
}

const GROUPS = [
  ["tile", "Ground materials"], ["building", "Buildings"], ["nature", "Trees and plants"], ["prop", "Props"],
  ["character", "Characters"], ["crop", "Crops"], ["portrait", "Dialog portraits"], ["ui", "UI, icons and effects"],
  ["menu", "Menus: icons, cursor, frames and buttons"],
];
const PRIORITY = { tile: 1, building: 2, nature: 3, character: 4, crop: 5, prop: 6, portrait: 7, ui: 8, menu: 9 };
const size = (s) => (s.kind === "static" ? `${s.w * SCALE}×${s.h * SCALE}` : sizeLabel(s));
// skin slots size themselves in PNG pixels
const needed = rows.filter((r) => !r.done);

let out = `# Sprite tracker

Generated by \`node tools/sprite-tracker.mjs\`. Don't edit by hand; re-run it after adding sprites or slots.

**${rows.length - needed.length} of ${rows.length} painted.** ${needed.length} still use code art or a template block.

- **To fill a slot:** save \`assets/sprites/<slot>.png\` and add it to \`assets/sprites/manifest.json\` (\`tools/prep-sprite.sh\` does both).
- **Guides:** each slot's guide is in \`assets/sprite-templates/blocks/<slot>.png\`, and \`sprites.html\` shows them all.
- **New slots:** the **Added** column says which update a slot arrived in, so new work is easy to spot.
- **Optional night versions:** for buildings and lanterns marked 🌙, add \`<slot>-night.png\` with lit windows.
- **Prompts:** every slot has a ready-to-paste image prompt and prep command in \`PROMPTS.md\` (click a slot name below).

## Still needed, in priority order

| | Slot | PNG size | Added | What it is |
| --- | --- | --- | --- | --- |
`;
for (const r of [...needed].sort((a, b) => (PRIORITY[a.cat] || 9) - (PRIORITY[b.cat] || 9)))
  out += `| ⬜ | [\`${r.name}\`](PROMPTS.md#${r.name.replace(/[^a-z0-9-]/g, "")})${r.night ? " 🌙" : ""} | ${size(r)} | ${r.since || "v1"} | ${r.desc} |\n`;

out += `\n## Everything, by group\n`;
for (const [cat, title] of GROUPS) {
  const g = rows.filter((r) => r.cat === cat);
  if (!g.length) continue;
  out += `\n### ${title} (${g.filter((r) => r.done).length}/${g.length})\n\n| | Slot | PNG size | Added |\n| --- | --- | --- | --- |\n`;
  for (const r of g) out += `| ${r.done ? "✅" : "⬜"} | \`${r.name}\`${r.night ? " 🌙" : ""} | ${size(r)} | ${r.since || "v1"} |\n`;
}
out += `\n## Drawn in code on purpose\n\nThese are effects rather than sprites: chimney smoke, festival bunting, fireflies, water ripples on the fountain, ground shadows, the day/night lighting and the fishing line.\n`;

fs.writeFileSync(path.join(root, "SPRITE_TRACKER.md"), out);
console.log(`SPRITE_TRACKER.md: ${rows.length - needed.length}/${rows.length} painted, ${needed.length} needed`);
