#!/usr/bin/env node
// Writes PROMPTS.md and assets/sprite-prompts.json: a ready-to-paste image-generator
// prompt for every sprite slot (and every prop in assets/world.json), with its size and
// the command that turns the raw image into the game's PNG.
//   node tools/sprite-prompts.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const { SLOTS, SCALE, sizeLabel } = await import(path.join(root, "js/sprites.js"));
const P = await import(path.join(root, "js/prompts.js"));

const painted = new Set((JSON.parse(fs.readFileSync(path.join(root, "assets/sprites/manifest.json"), "utf8")).files || []).map((f) => f.replace(/\.png$/i, "")));
const world = JSON.parse(fs.readFileSync(path.join(root, "assets/world.json"), "utf8"));
const slots = [...SLOTS];
for (const d of world.decor || []) {
  if (slots.some((s) => s.name === d.name)) continue;
  const [pw, ph] = d.size || [(d.w || 1) * 32, (d.h || 1) * 32];
  slots.push({ name: d.name, kind: "static", w: pw / SCALE, h: ph / SCALE, fw: d.w || 1, fh: d.h || 1, cat: d.category || "prop", since: "world.json", prompt: d.prompt || d.title, desc: d.title || d.name });
}

const GROUPS = [
  ["tile", "Ground materials", "Seamless textures. Generate, then crop or resize to the strip size."],
  ["building", "Buildings", "One building per image. The prep script trims and stands it on the bottom edge."],
  ["nature", "Trees and plants", ""],
  ["prop", "Props", ""],
  ["character", "Characters", "Image generators struggle with exact grids: generate each frame (or just the front view) separately and assemble with tools/make-sheet.sh. Keep one reference image of the character and reuse it for every frame."],
  ["crop", "Crops", "Four growth stages per crop."],
  ["portrait", "Dialog portraits", ""],
  ["ui", "In-game UI: bubbles, seeds, fish, icons", "Tiny images: keep shapes bold and simple so they read at 32×32."],
  ["menu", "Menus: icons, cursor, frames and buttons", "Frames are 9-slice: corners stay put and edges stretch, so keep edges plain and even. Until painted, menus keep their current look and emoji."],
];
const size = (s) => (s.kind === "static" ? `${s.w * SCALE}×${s.h * SCALE}` : sizeLabel(s));
const rows = slots.map((s) => ({ name: s.name, group: s.cat, kind: s.kind, size: size(s), since: s.since || "v1", painted: painted.has(s.name), file: `assets/sprites/${s.name}.png`, guide: `assets/sprite-templates/blocks/${s.name}.png`, prompt: P.fullPrompt(s), prep: P.prepCommand(s), night: !!s.night }));

fs.writeFileSync(path.join(root, "assets/sprite-prompts.json"), JSON.stringify({ style: P.STYLE, slots: rows }, null, 2));

let md = `# Sprite prompts

Generated by \`node tools/sprite-prompts.mjs\` from \`js/prompts.js\`. Edit the wording there, not here.

A ready-to-paste image-generator prompt for each of the game's ${rows.length} sprite slots, grouped like \`SPRITE_TRACKER.md\` (ground first: it covers the most screen). Each one includes the shared style (matching the concept paintings in \`assets/\`), the exact size, the camera view and a flat magenta background that the prep scripts remove.

**Workflow for one slot**
1. Paste the prompt into your image generator. Attach a concept painting from \`assets/\` as a style reference if your tool allows it.
2. Save the result as \`raw.png\` and run the **prep** command under the prompt. It removes the background, sizes the image and adds it to \`assets/sprites/manifest.json\`.
3. Check it in the game (press **B** for blocks view to see what's still missing) and in \`sprites.html\`, which also shows each slot's block guide.

**Tips**
- **Keep a look consistent:** generate the farmhouse first and reuse it as a reference for the other buildings. Do the same with the robot for every robot variant.
- **Night versions** (🌙, optional): run the same prompt with "at night, warm glowing windows", save it as \`<slot>-night\`, and prep it the same way.
- **Machine-readable copy:** every prompt is also in \`assets/sprite-prompts.json\`, for batch tools.

`;
md += `## Contents\n\n${GROUPS.map(([g, t]) => `- [${t}](#${t.toLowerCase().replace(/[^a-z0-9 -]/g, "").replace(/ /g, "-")}) (${rows.filter((r) => r.group === g).length})`).join("\n")}\n`;
for (const [g, title, note] of GROUPS) {
  const list = rows.filter((r) => r.group === g);
  if (!list.length) continue;
  md += `\n## ${title}\n\n${note ? `${note}\n` : ""}`;
  for (const r of list) {
    md += `\n### ${r.name}\n\n${r.painted ? "✅ painted · " : ""}**Size** ${r.size} · **Added** ${r.since} · **Guide** \`${r.guide}\`${r.night ? " · 🌙 optional night version" : ""}\n\n\`\`\`text\n${r.prompt}\n\`\`\`\n\n**Prep** \`${r.prep}\`\n`;
  }
}
fs.writeFileSync(path.join(root, "PROMPTS.md"), md);
console.log(`PROMPTS.md and assets/sprite-prompts.json: ${rows.length} prompts`);
